// <auto-generated />
namespace _03_MVA_Ex_RepoPatern.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_database));
        
        string IMigrationMetadata.Id
        {
            get { return "201708132216147_create_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
